#!/usr/bin/env bash
export OS_AUTH_URL=http://192.168.128.130:5000/v3
#export OS_PROJECT_ID=admin
export OS_PROJECT_NAME="admin"
export OS_USER_DOMAIN_NAME="Default"
export OS_PROJECT_DOMAIN_ID="default"
export OS_USERNAME="admin"
export OS_PASSWORD="Lw658hgBNaB34jnwSTAN8rISzBYrRQNt"
export OS_REGION_NAME="microstack"
export OS_INTERFACE=public
export OS_IDENTITY_API_VERSION=3
export OS_INSECURE=1
